### ISSUE TITLE
Option to add operationId

### ISSUE THREAD

**Issue by vincent-vade** [ShogunPanda/fastify-openapi-docs#11]
Hi,

First the package work pretty well. 
I would like to know if it's possible to add operationId inside the context of an handler ?

like:

```
{
  schema: {
    ...otherSchema
  },
  config: {
    hideHead: true,
    openapi: {
      operationId: "getUserById",
    },
  },
}
```
Because as i try the operationId is omit from the final openapi result.

Best regards

Vincent

**Comment by vincent-vade** [comment]
Ok i find it in local... I'll create a PR

**Comment by ShogunPanda** [comment]
Amazing. Thanks! For the time being, I'm closing this.
