### ISSUE TITLE
config does not exist in type FastifySchema

### ISSUE THREAD

**Issue by sittingbool** [ShogunPanda/fastify-openapi-docs#4]
Setting up the example in typescript I am getting the following error: TS2322: Type '{ config: {}; body: { $ref: string; }; }' is not assignable to type 'FastifySchema'.   Object literal may only specify known properties, and 'config' does not exist in type 'FastifySchema'.

**Comment by sittingbool** [comment]
Found it. Need to put this one level up, not in schema but next to it. Sorry

**Comment by ShogunPanda** [comment]
No worries, glad you solved it!
