### ISSUE TITLE
Redirect issue with ignoreTrailingSlash and the ui

### ISSUE THREAD

**Issue by SomethingSexy** [ShogunPanda/fastify-openapi-docs#5]
If looks like if the fastify option `ignoreTrailingSlash` is set to true that we get stuck in a redirect loop when trying to access the ui at `/docs`. Is there away this library can be updated to work with that option enabled?

```
  const app = fastify({
    ignoreTrailingSlash: true,
  })
```

**Comment by ShogunPanda** [comment]
Release in [v2.0.3](https://github.com/ShogunPanda/fastify-openapi-docs/releases/tag/v2.0.3)
