### ISSUE TITLE
Referencing definitions producing errors

### ISSUE THREAD

**Issue by michelle54725** [ShogunPanda/fastify-openapi-docs#9]
Hi,

I have a schema that looks like this:
```
export const VisibilityOptionsSchema = {
  type: 'object',
  $id: 'VisibilityOptions',
  description: "Visibility options for each field in User schema. Allowed values: 'hidden' / 'shown' / 'alwaysShown'.",
  properties: {
    id: { $ref: '#/definitions/options' },
    name: { $ref: '#/definitions/options' },
    sexuality: { $ref: '#/definitions/options' },
    age: { $ref: '#/definitions/options' },
    ...
  },
  additionalProperties: false,
  definitions: {
    options: {
      type: 'string',
      enum: ['hidden', 'shown', 'alwaysShown'],
    },
  },
};
```

**It works as intended as can see here the enum restriction is enforced:**

![image](https://user-images.githubusercontent.com/28771021/206271591-7e511bf3-190b-473b-8604-ec544e5ab8f4.png)

**However, in OpenAPI we get these errors:**

![image](https://user-images.githubusercontent.com/28771021/206272144-a8f876bd-99bc-4695-8035-d5693df4b45f.png)

The functionality is not affected but any idea why the reference isn't recognized?

**Comment by ShogunPanda** [comment]
Hi! First of all, sorry for the very late reply.

This is expected as the link is resolved from two different roots: one is your schema in the context of fastify, the other one is the entire document in the context of OpenAPI.

Luckily for you, and completely undocumented (my bad) you can fix this with this workaround:

* Extract the referenced part of your schema in a separate schema with a different $id.
* Add the schema to fastify using `fastify.addSchema`.
* Use the reference in fastify by appending a `#`. (which will be ignored by fastify and replaced by fastify-openapi-docs when generating the documentation output.

In your case:

```
const VisibilityOptionsOptionsSchema = {
  $id: 'definitions-visibilityOptions-options', // Note that here you cannot use / as it is used for path traversing
  type: 'string',
  enum: ['hidden', 'shown', 'alwaysShown']
}

const VisibilityOptionsSchema = {
  $id: 'VisibilityOptions',
  type: 'object',
  description: "Visibility options for each field in User schema. Allowed values: 'hidden' / 'shown' / 'alwaysShown'.",
  properties: {
    id: { $ref: 'definitions-visibilityOptions-options#' } // The # is used by openapi-docs to recognized when we have to manipulate the reference in the generated documentation file.
  },
  additionalProperties: false
}

const server = fastify()
server.addSchema(VisibilityOptionsOptionsSchema)

// Continue
```

Let me know if this fixes your problem. For now I'm closing the issue.
